(ns tesseraft.contract.paths
  (:require [babashka.fs :as fs]
            [clojure.string :as str]))

(defn workflow-dir [wf] (:__dir wf "."))
(defn workflow-file [wf] (:__file wf))
(defn workflow-name [wf] (or (get-in wf [:metadata :name]) (:name wf)))
(defn node-package-dir [pkg] (:__dir pkg "."))
(defn node-package-file [pkg] (:__file pkg))
(defn node-package-name [pkg] (get-in pkg [:metadata :name]))
(defn fragment-package-dir [pkg] (:__dir pkg "."))
(defn fragment-package-file [pkg] (:__file pkg))
(defn fragment-package-name [pkg] (get-in pkg [:metadata :name]))
(defn resolve-fragment-package-path [pkg p] (when p (str (fs/path (fragment-package-dir pkg) p))))
(defn resolve-workflow-path [wf p] (when p (str (fs/path (workflow-dir wf) p))))
(defn resolve-node-package-path [pkg p] (when p (str (fs/path (node-package-dir pkg) p))))
(defn absolute-path? [s] (and (string? s) (str/starts-with? s "/")))
(defn relative-path-components [s] (str/split (str s) #"/"))
(defn contains-parent-segment? [s] (some #{".."} (relative-path-components s)))
(defn contains-dot-segment? [s] (some #{"." ".."} (relative-path-components s)))
(defn windows-drive-qualified-path? [s] (and (string? s) (boolean (re-find #"^[A-Za-z]:" s))))
(defn portable-absolute-path? [s] (and (string? s) (or (str/starts-with? s "/") (str/starts-with? s "\\\\") (windows-drive-qualified-path? s))))
(defn safe-relative-path? [s] (and (string? s) (not (str/blank? s)) (not (absolute-path? s)) (not (contains-parent-segment? s))))
(defn safe-relative-prefix? [s] (and (safe-relative-path? s) (not (portable-absolute-path? s)) (not (str/includes? s "\\")) (not (contains-dot-segment? s))))
