(ns tesseraft.executors.mock
  (:require
    [tesseraft.executors.pi-cli :as pi-cli]
    [tesseraft.spec :as spec]
    [tesseraft.runtime.store :as store]
    [babashka.fs :as fs]
    [clojure.string :as str]))

(defn artifact-path [ctx p]
  (let [rendered (spec/render-template-string p ctx)]
    (if (str/starts-with? rendered "/") rendered (str (fs/path (get-in ctx [:run :dir]) rendered)))))

(defn write-text! [path text]
  (fs/create-dirs (fs/parent path))
  (spit path text))

(defn status-output? [k node]
  (or (= :status k)
      (= (spec/output-path (get-in node [:outputs k])) (spec/status-output-path node))))

(defn json-path? [path]
  (when-let [ext (fs/extension path)]
    (= "json" (str/lower-case (str ext)))))

(defn placeholder-value [ctx state-id output-key path]
  (cond
    (json-path? path) {:status "ok" :mock true :state (name state-id) :output (name output-key)}
    (= output-key :branch-name) (or (get-in ctx [:inputs :branch]) (str "feature/mock-" (get-in ctx [:run :id])))
    (= output-key :title) (str "Mock dry-run PR for " (get-in ctx [:workflow :name]))
    (= output-key :body) (str "# Mock dry-run PR\n\nGenerated by Tesseraft mock executor for `" (name state-id) "`.\n")
    :else (str "Mock executor dry-run artifact for `" (name state-id) "` / `" (name output-key) "`.\n")))

(defn write-output! [ctx state-id node [output-key contract]]
  (when (spec/output-required? contract)
    (let [path (artifact-path ctx (spec/output-path contract))]
      (if (status-output? output-key node)
        (store/write-json! path {:status "pass"
                                 :summary "Mock executor dry-run pass"
                                 :issues_file nil})
        (let [value (placeholder-value ctx state-id output-key path)]
          (if (map? value)
            (store/write-json! path value)
            (write-text! path value)))))))

(defn run-agent-node! [wf ctx state-id node]
  (let [prompt-file (pi-cli/render-prompt! wf ctx state-id node)
        log-file (str (fs/path (get-in ctx [:run :dir]) "logs" (str (name state-id) "-mock-" (get-in ctx [:run :attempt]) ".log")))]
    (doseq [output (spec/output-contracts node)]
      (write-output! ctx state-id node output))
    (fs/create-dirs (fs/parent log-file))
    (spit log-file (str "MOCK EXECUTOR\n\nPROMPT_FILE: " prompt-file "\nSTATE: " (name state-id) "\n"))
    {:executor "mock"
     :ok true
     :status "pass"
     :mock true
     :prompt-file prompt-file
     :log-file log-file}))
