(ns tesseraft.adapters.builtin
  (:require
    [tesseraft.capabilities.handlers :as handler-catalog]
    [tesseraft.handlers.common :as common]
    [tesseraft.handlers.git :as git]
    [tesseraft.handlers.github :as github]
    [tesseraft.handlers.noop :as noop]
    [tesseraft.handlers.web :as web]))

(def ^:dynamic *process-extra-env* {})
(def shell! common/shell!)
(def run-dir common/run-dir)
(def artifact-path common/artifact-path)
(def write-artifact-json! common/write-artifact-json!)
(def artifact-text common/artifact-text)
(def rendered-runtime-cwd common/rendered-runtime-cwd)
(def repo-dir common/repo-dir)
(def render-command git/render-command)
(def branch-name git/branch-name)
(def git-ref-candidates git/git-ref-candidates)
(def git-ref-exists? git/git-ref-exists?)
(def base-ref git/base-ref)
(def git-user-config git/git-user-config)
(def git-user-args git/git-user-args)
(def git-ensure-branch! git/git-ensure-branch!)
(def safe-path-component git/safe-path-component)
(def absolute-normal-path git/absolute-normal-path)
(def inside-dir? git/inside-dir?)
(def worktree-dir git/worktree-dir)
(def current-worktree-branch git/current-worktree-branch)
(def git-worktree? git/git-worktree?)
(def worktree-path-for-branch git/worktree-path-for-branch)
(def ensure-worktree-path! git/ensure-worktree-path!)
(def git-ensure-worktree! git/git-ensure-worktree!)
(def git-push! git/git-push!)
(def github-token github/github-token)
(def github-command-opts github/github-command-opts)
(def github-repo! github/github-repo!)
(def non-empty-string github/non-empty-string)
(def parse-uri github/parse-uri)
(def uri-path-segments github/uri-path-segments)
(def integer-string? github/integer-string?)
(def github-api-pr-url->browser-url github/github-api-pr-url->browser-url)
(def github-browser-pr-url? github/github-browser-pr-url?)
(def github-pr-url github/github-pr-url)
(def github-existing-pr github/github-existing-pr)
(def github-ssh-repo-url github/github-ssh-repo-url)
(def github-create-pr! github/github-create-pr!)
(def gh-api-all github/gh-api-all)
(def github-fetch-pr-feedback! github/github-fetch-pr-feedback!)
(def java-pid web/java-pid)
(def read-line-with-timeout web/read-line-with-timeout)
(def wait-for-http-ok web/wait-for-http-ok)
(def wait-for-http-body-contains web/wait-for-http-body-contains)
(def start-test-server! web/start-test-server!)
(def stop-test-server! web/stop-test-server!)
(def capture-ui-evidence! web/capture-ui-evidence!)
(def required-ui-checks web/required-ui-checks)
(def ui-validation-issue web/ui-validation-issue)
(def read-required-json web/read-required-json)
(def report-contradiction web/report-contradiction)
(def validate-ui-review! web/validate-ui-review!)
(def github-slug-from-remote web/github-slug-from-remote)
(def publish-visual-evidence! web/publish-visual-evidence!)
(def output-path common/output-path)
(def mock-pr github/mock-pr)
(def mock-worktree-dir git/mock-worktree-dir)
(def mock-test-server web/mock-test-server)
(def mock-git-ensure-branch! git/mock-git-ensure-branch!)
(def mock-git-ensure-worktree! git/mock-git-ensure-worktree!)
(def mock-git-push! git/mock-git-push!)
(def mock-github-create-pr! github/mock-github-create-pr!)
(def mock-github-fetch-pr-feedback! github/mock-github-fetch-pr-feedback!)
(def mock-start-test-server! web/mock-start-test-server!)
(def mock-stop-test-server! web/mock-stop-test-server!)
(def mock-capture-ui-evidence! web/mock-capture-ui-evidence!)
(def mock-validate-ui-review! web/mock-validate-ui-review!)
(def mock-publish-visual-evidence! web/mock-publish-visual-evidence!)
(def noop-succeed! noop/noop-succeed!)
(def mock-noop-succeed! noop/mock-noop-succeed!)

(def handlers handler-catalog/descriptors)

(defn run-mock-handler! [wf ctx state-id node]
  (binding [common/*process-extra-env* *process-extra-env*]
    (handler-catalog/invoke! (:handler node) :mock wf ctx state-id node)))

(defn run-handler!
  ([wf ctx state-id node] (run-handler! wf ctx state-id node {}))
  ([wf ctx state-id node opts]
   (binding [common/*process-extra-env* *process-extra-env*]
     (if (:mock? opts)
       (handler-catalog/invoke! (:handler node) :mock wf ctx state-id node)
       (handler-catalog/invoke! (:handler node) :run wf ctx state-id node)))))
