(ns tesseraft.control-plane.core
  (:require
    [tesseraft.control-plane.common :as common]
    [tesseraft.control-plane.approvals :as approvals]
    [tesseraft.control-plane.projects :as projects]
    [tesseraft.control-plane.runs :as runs]
    [tesseraft.control-plane.settings :as settings-service]
    [tesseraft.control-plane.workflows :as workflows]))

(def default-options common/default-options)
(def opts common/opts)
(def api-value common/api-value)
(def error-response common/error-response)
(def abs-path common/abs-path)
(def path-prefix? common/path-prefix?)
(def relative-path common/relative-path)
(def tesseraft-home common/tesseraft-home)
(def valid-project-id? projects/valid-project-id?)
(def slugify-project-name projects/slugify-project-name)
(def credential-ref? projects/credential-ref?)
(def normalize-work-tracker projects/normalize-work-tracker)
(def list-work-tracker-providers projects/list-work-tracker-providers)
(def list-capabilities projects/list-capabilities)
(def project-registry-path projects/project-registry-path)
(def invalid-project-registry-response projects/invalid-project-registry-response)
(def read-project-registry projects/read-project-registry)
(def read-project-registration projects/read-project-registration)
(def project-connection-source projects/project-connection-source)
(def read-project-descriptor projects/read-project-descriptor)
(def list-project-manifests projects/list-project-manifests)
(def read-credentials projects/read-credentials)
(def valid-local-credential-store? projects/valid-local-credential-store?)
(def local-credential-value projects/local-credential-value)
(def production-credential-resolver projects/production-credential-resolver)
(def resolve-credential projects/resolve-credential)
(def synthesize-default-project projects/synthesize-default-project)
(def resolve-project projects/resolve-project)
(def list-projects projects/list-projects)
(def get-project projects/get-project)
(def create-project projects/create-project)
(def unregister-project projects/unregister-project)
(def update-project projects/update-project)
(def mask-credential projects/mask-credential)
(def get-project-connections projects/get-project-connections)
(def work-tracker-diagnosis projects/work-tracker-diagnosis)
(def work-tracker-config-diagnosis projects/work-tracker-config-diagnosis)
(def work-tracker-credential-diagnosis projects/work-tracker-credential-diagnosis)
(def update-project-connections projects/update-project-connections)
(def project-context-opts projects/project-context-opts)
(def project-scoped-opts projects/project-scoped-opts)
(def discovery-roots workflows/discovery-roots)
(def package-files workflows/package-files)
(def workflow-files workflows/workflow-files)
(def workflow-file-entries workflows/workflow-file-entries)
(def fragment-file-entries workflows/fragment-file-entries)
(def fragment-files workflows/fragment-files)
(def fragment-candidates workflows/fragment-candidates)
(def resolve-fragment workflows/resolve-fragment)
(def lint-summary workflows/lint-summary)
(def read-workflow-entry workflows/read-workflow-entry)
(def entry-name workflows/entry-name)
(def select-visible-workflow-entries workflows/select-visible-workflow-entries)
(def workflow-meta-item workflows/workflow-meta-item)
(def shadowing-for-visible workflows/shadowing-for-visible)
(def list-workflows workflows/list-workflows)
(def workflow-candidates workflows/workflow-candidates)
(def resolve-workflow workflows/resolve-workflow)
(def get-workflow workflows/get-workflow)
(def edge-from-transition workflows/edge-from-transition)
(def get-workflow-graph workflows/get-workflow-graph)
(def nested-fragment-run-state-file? runs/nested-fragment-run-state-file?)

(def run-state-files runs/run-state-files)
(def run-dir-from-state-file runs/run-dir-from-state-file)
(def staleness-threshold-seconds runs/staleness-threshold-seconds)
(def seconds-since runs/seconds-since)
(def latest-event-at runs/latest-event-at)
(def derive-liveness runs/derive-liveness)
(def run-summary runs/run-summary)
(def list-runs runs/list-runs)
(def matching-run-files runs/matching-run-files)
(def resolve-run runs/resolve-run)
(def events-file runs/events-file)
(def read-events-file runs/read-events-file)
(def event-name runs/event-name)
(def nonzero-exit-code? runs/nonzero-exit-code?)
(def result-error? runs/result-error?)
(def result-error-summary runs/result-error-summary)
(def attempt-status runs/attempt-status)
(def derive-attempts-from-events runs/derive-attempts-from-events)
(def attempts-from-context runs/attempts-from-context)
(def internal-attempts-for-parent-attempt runs/internal-attempts-for-parent-attempt)
(def attach-internal-attempts runs/attach-internal-attempts)
(def preview-limit runs/preview-limit)
(def scan-file-limit runs/scan-file-limit)
(def max-read-size runs/max-read-size)
(def reject-artifact-path runs/reject-artifact-path)
(def path-starts-with? runs/path-starts-with?)
(def safe-artifact-path runs/safe-artifact-path)
(def existing-safe-file runs/existing-safe-file)
(def rel-from-run runs/rel-from-run)
(def content-type runs/content-type)
(def previewable? runs/previewable?)
(def artifact-meta runs/artifact-meta)
(def declared-output-artifacts runs/declared-output-artifacts)
(def artifact-key-regex runs/artifact-key-regex)
(def artifact-path-values runs/artifact-path-values)
(def run-relative-string runs/run-relative-string)
(def event-artifacts runs/event-artifacts)
(def scan-artifacts runs/scan-artifacts)
(def dedupe-artifacts runs/dedupe-artifacts)
(def list-artifacts* runs/list-artifacts*)
(def get-run-artifacts runs/get-run-artifacts)
(def read-run-artifact runs/read-run-artifact)
(def issues-artifact-has-issues? runs/issues-artifact-has-issues?)
(def failures-from-run runs/failures-from-run)
(def get-run runs/get-run)
(def get-run-events runs/get-run-events)
(def delete-run runs/delete-run)
(def approvals-dir approvals/approvals-dir)
(def comments-file approvals/comments-file)
(def load-approval-summary approvals/load-approval-summary)
(def load-approval approvals/load-approval)
(def get-run-approvals approvals/get-run-approvals)
(def get-run-approval approvals/get-run-approval)
(def get-run-comments approvals/get-run-comments)
(def timestamp approvals/timestamp)
(def random-id approvals/random-id)
(def add-run-comment approvals/add-run-comment)
(def validate-git-user settings-service/validate-git-user)
(defn get-git-user
  ([] (get-git-user {} nil))
  ([options] (get-git-user options nil))
  ([options project-id] (settings-service/get-git-user (opts options) project-id)))
(defn set-git-user
  ([options name email global?] (set-git-user options name email global? nil))
  ([options name email global? project-id] (settings-service/set-git-user (opts options) name email global? project-id)))
(defn get-settings
  ([] (get-settings {} nil))
  ([options] (get-settings options nil))
  ([options _project-id] (settings-service/get-settings (opts options))))
(defn set-settings
  ([options updates] (set-settings options updates false nil))
  ([options updates global?] (set-settings options updates global? nil))
  ([options updates _global? _project-id] (settings-service/set-settings (opts options) updates)))
